### ISSUE TITLE
Why it is highly recommended to use vcpkg as a Git submodule?

### ISSUE THREAD

**Issue by mloskot** [lukka/CppBuildTasks#24]
Currently, the README says:

> It is highly recommended to use vcpkg as a Git submodule. 

and 

> when vcpkg is NOT a submodule (not recommended)

I believe it would be useful if FAQ offered an explanation of what are the reasons a submodule is the recommended way to set it up.

**Comment by lukka** [comment]
You could read the explanation on a following paragraph: [use-vcpkg-as-a-submodule-of-your-git-repository](https://github.com/lukka/CppBuildTasks#use-vcpkg-as-a-submodule-of-your-git-repository).

Just a recap: 

- When you use `vcpkg` you need to ensure you use exactly the expected version established by the consumer (i.e. a Git repo);

- The version is determined by the commit id/tag in the `vcpkg`'s Git repository;

- One good approach is to store the commit id in the repo that consumes `vcpkg` using a Git submodule;


When `vcpkg` is listed as a dependency and the exact version is not stated, this is potentially leading to unexpected results. For example, you would get different results when building with `vcpkg` that contains `randomLibraryNameVersion1` vs `vcpkg` that contains `randomLibraryNameVersion2`.

Do not hesitate to provide feedback or a PR in order to make docs more clear and exhaustive.

**Comment by mloskot** [comment]
That addresses my question. Thanks. 

Since lazy me had not read the README beyond the Quickstart, I did not find that section. 
I have just submitted a tiny PR #25 which should help reader to find the important section.
